const cards = [
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
  {
    id: 1,
    daily: "Daily Mix",
    tracks: "12 Tracks",
    option: "Frontend Radio",
    pic: "https://nextui-docs-v2.vercel.app/images/hero-card-complete.jpeg",
  },
];
export default cards;
